### ISSUE TITLE
[PR] Security 설정 추가 및 권한, 이메일 기능 추가

### ISSUE THREAD

**Issue by hskimmm** [HalfHalfJavaMany/SpringBoot_Project#50]
## Description
1. Security 설정 추가
2. 회원가입 이메일 중복 처리 기능 추가
3. 정지일 이후 정지 해제 코드 수정
4. 권한 변경 시 auth 컬럼 수정

## Change Log
추가한 내용 혹은 변경된 내용을 간략하게 설명해주세요.

## Issue Tags
- Closed | Fixed: #issue_number

**Comment by barabamBam** [comment]
#51
